import {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Building2,
  Calendar,
  CalendarClock,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDot,
  ClipboardList,
  ClipboardPlus,
  Clock,
  Coins,
  Copy,
  FileCheck2,
  FileText,
  Flame,
  Gem,
  Hammer,
  HardHat,
  HelpCircle,
  Image as ImageIcon,
  Layers,
  Map,
  MapPin,
  MapPinned,
  Menu,
  MessageSquareMore,
  MessageSquareWarning,
  Moon,
  Mountain,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Pointer,
  Repeat,
  Reply,
  Search,
  Send,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Stamp,
  Sparkles,
  Star,
  Target,
  Trash2,
  Truck,
  User,
  UserPlus,
  UserRound,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  "building-2": Building2,
  mountain: Mountain,
  wrench: Wrench,
  zap: Zap,
  users: Users,
  user: User,
  search: Search,
  "settings-2": Settings2,
  "message-square-more": MessageSquareMore,
  "user-round": UserRound,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  menu: Menu,
  plus: Plus,
  send: Send,
  camera: Camera,
  image: ImageIcon,
  paperclip: Paperclip,
  "clipboard-list": ClipboardList,
  "clipboard-plus": ClipboardPlus,
  "help-circle": HelpCircle,
  pin: Pin,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  "alert-triangle": AlertTriangle,
  activity: Activity,
  moon: Moon,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "file-text": FileText,
  x: X,
  pencil: Pencil,
  "user-plus": UserPlus,
  map: Map,
  "badge-check": BadgeCheck,
  pointer: Pointer,
  reply: Reply,
  copy: Copy,
  "trash-2": Trash2,
  clock: Clock,
  "file-check-2": FileCheck2,
  stamp: Stamp,
  "check-circle-2": CheckCircle2,
  repeat: Repeat,
  gem: Gem,
  "message-square-warning": MessageSquareWarning,
  check: Check,
  "calendar-clock": CalendarClock,
  calendar: Calendar,
  coins: Coins,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  target: Target,
  layers: Layers,
  "circle-dot": CircleDot,
  sparkles: Sparkles,
  "hard-hat": HardHat,
  star: Star,
  truck: Truck,
  hammer: Hammer,
  flame: Flame,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? CircleDot;
}
