import { ME_ID } from "./types";
import type {
  Agenda,
  Contact,
  ContractorCompany,
  Me,
  Message,
  Room,
  Site,
  Trade,
  TradeRequest,
  WeeklyTotalRow,
  Zone,
} from "./types";

export const seedRooms: Room[] = [
  {
    id: "room-arch",
    type: "trade",
    name: "건축방",
    icon: "building-2",
    memberCount: 24,
    unread: 5,
    time: "오후 2:14",
    pinned: true,
    creator: "c-kim-sh",
    members: [ME_ID, "c-kim-sh", "c-park-jm", "c-lee-ht"],
  },
  {
    id: "room-civil",
    type: "trade",
    name: "토목방",
    icon: "mountain",
    memberCount: 18,
    unread: 2,
    time: "오후 1:02",
    creator: ME_ID,
    members: [ME_ID],
  },
  {
    id: "room-mep",
    type: "trade",
    name: "설비방",
    icon: "wrench",
    memberCount: 15,
    time: "오전 11:47",
    creator: "c-choi-jw",
    members: [ME_ID, "c-choi-jw", "c-jung-wj"],
  },
  {
    id: "room-elec",
    type: "trade",
    name: "전기방",
    icon: "zap",
    memberCount: 12,
    time: "오전 9:30",
    creator: ME_ID,
    members: [ME_ID],
  },
  {
    id: "room-partner",
    type: "partner",
    name: "협력사 단톡방",
    icon: "users",
    memberCount: 41,
    unread: 12,
    time: "오전 8:55",
    creator: ME_ID,
    members: [ME_ID, "c-kim-sh", "c-park-jm", "c-lee-ht", "c-choi-jw", "c-jung-wj"],
  },
  {
    id: "room-dm-kim",
    type: "dm",
    name: "김공무 과장",
    icon: "user",
    time: "어제",
    creator: ME_ID,
    members: [ME_ID],
  },
];

export const seedMessages: Message[] = [
  // ---- room-arch ----
  { id: "m-a-1", roomId: "room-arch", kind: "system", text: "2026년 4월 27일 (월)", time: "" },
  {
    id: "m-a-2",
    roomId: "room-arch",
    sender: "이형탁 소장",
    kind: "text",
    text: "B동 지하 1층 옹벽구간 착공 전, 이음부 처리 방식 사전검토 부탁드립니다.",
    time: "10:02",
  },
  { id: "m-a-3", roomId: "room-arch", kind: "agenda-card", agendaNo: 128, time: "10:04" },
  { id: "m-a-4", roomId: "room-arch", kind: "system", text: "2026년 7월 28일 (화)", time: "" },
  {
    id: "m-a-5",
    roomId: "room-arch",
    sender: "이형탁 소장",
    kind: "text",
    text: "3층 슬래브 배근 완료됐는데 피복두께가 도면보다 얇아 보입니다.",
    time: "2:09",
  },
  {
    id: "m-a-6",
    roomId: "room-arch",
    sender: "이형탁 소장",
    kind: "photo",
    photoLabel: "사진 — 3층 슬래브 배근 현장",
    time: "2:10",
  },
  {
    id: "m-a-7",
    roomId: "room-arch",
    kind: "text",
    text: "도면 확인해볼게요. 구조 검토서 첨부합니다.",
    time: "2:12",
    outgoing: true,
  },
  {
    id: "m-a-8",
    roomId: "room-arch",
    kind: "file",
    fileName: "구조검토_A동_3F.pdf",
    fileSize: "1.8 MB",
    time: "2:12",
    outgoing: true,
  },
  { id: "m-a-9", roomId: "room-arch", kind: "agenda-card", agendaNo: 153, time: "2:14" },
  {
    id: "m-a-10",
    roomId: "room-arch",
    sender: "박품질 부장",
    kind: "text",
    text: "안건방에서 조치 방안 논의하시죠. 감리단도 참여시키겠습니다.",
    time: "2:14",
  },
  {
    id: "m-a-11",
    roomId: "room-arch",
    sender: "이형탁 소장",
    kind: "text",
    text: "B동 지하 1층 옹벽 이음부에서 누수 흔적이 확인됐습니다.",
    time: "3:40",
  },
  {
    id: "m-a-12",
    roomId: "room-arch",
    sender: "이형탁 소장",
    kind: "photo",
    photoLabel: "사진 — 이음부 누수 흔적 (2장)",
    time: "3:41",
  },
  { id: "m-a-13", roomId: "room-arch", kind: "agenda-card", agendaNo: 167, time: "3:42" },

  // ---- room-civil ----
  { id: "m-c-1", roomId: "room-civil", kind: "system", text: "오늘", time: "" },
  {
    id: "m-c-2",
    roomId: "room-civil",
    sender: "정토목 과장",
    kind: "text",
    text: "되메우기 다짐 시험 결과 공유합니다.",
    time: "1:00",
  },
  { id: "m-c-3", roomId: "room-civil", kind: "agenda-card", agendaNo: 154, time: "1:02" },

  // ---- room-mep ----
  { id: "m-m-1", roomId: "room-mep", kind: "system", text: "오늘", time: "" },
  {
    id: "m-m-2",
    roomId: "room-mep",
    sender: "한설비 대리",
    kind: "text",
    text: "지하 1층 소화배관 루트 협의 필요합니다.",
    time: "11:40",
  },
  { id: "m-m-3", roomId: "room-mep", kind: "agenda-card", agendaNo: 155, time: "11:45" },
  { id: "m-m-4", roomId: "room-mep", kind: "agenda-card", agendaNo: 156, time: "11:47" },

  // ---- room-elec ----
  { id: "m-e-1", roomId: "room-elec", kind: "system", text: "오늘", time: "" },
  {
    id: "m-e-2",
    roomId: "room-elec",
    sender: "최전기 기사",
    kind: "text",
    text: "전기실 트레이 반입 일정 조율 건 확인 부탁드립니다.",
    time: "9:30",
  },

  // ---- room-partner ----
  { id: "m-p-1", roomId: "room-partner", kind: "system", text: "오늘", time: "" },
  {
    id: "m-p-2",
    roomId: "room-partner",
    sender: "동부기초",
    kind: "text",
    text: "금일 크레인 반입 완료했습니다.",
    time: "8:55",
  },

  // ---- room-dm-kim ----
  { id: "m-k-1", roomId: "room-dm-kim", kind: "system", text: "어제", time: "" },
  {
    id: "m-k-2",
    roomId: "room-dm-kim",
    sender: "김공무 과장",
    kind: "text",
    text: "기성 서류 검토 후 회신드리겠습니다.",
    time: "5:30",
  },

  // ---- agenda-153 subroom ----
  {
    id: "m-153-1",
    roomId: "agenda-153",
    sender: "김대리",
    kind: "text",
    text: "슬래브 철근 피복이 부족해 보입니다. 이대로 타설 가능할까요?",
    time: "2:16",
  },
  {
    id: "m-153-2",
    roomId: "agenda-153",
    sender: "김대리",
    kind: "photo",
    photoLabel: "사진 — 피복두께 실측",
    time: "2:16",
  },
  {
    id: "m-153-3",
    roomId: "agenda-153",
    sender: "품질팀",
    kind: "text",
    text: "스페이서 상태와 실제 피복두께를 다시 측정해 주세요.",
    time: "2:19",
  },
  {
    id: "m-153-4",
    roomId: "agenda-153",
    sender: "현장소장",
    kind: "text",
    text: "간격보다 피복 확보가 우선입니다. 부족 구간은 재배근하세요.",
    time: "2:24",
    isDecisionBasis: true,
  },
  {
    id: "m-153-5",
    roomId: "agenda-153",
    kind: "text",
    text: "재배근 완료했습니다",
    time: "4:41",
    outgoing: true,
  },

  // ---- agenda-167 subroom ----
  {
    id: "m-167-1",
    roomId: "agenda-167",
    sender: "이형탁 소장",
    kind: "text",
    text: "3개월 전 사전검토(#128)에서 우려했던 부위와 정확히 일치합니다.",
    time: "3:44",
  },
];

export const seedAgendas: Agenda[] = [
  {
    no: 128,
    parentRoomId: "room-arch",
    title: "B동 지하 1층 옹벽 이음부 누수 위험 사전검토",
    status: "사전검토",
    participants: 4,
    createdLabel: "착공 전 등록",
    floorplanLabel: "B동 B1F 평면 · 핀 지정",
    pin: { x: 78, y: 25 },
    updatedLabel: "D-92",
  },
  {
    no: 167,
    parentRoomId: "room-arch",
    title: "B동 지하 1층 옹벽 이음부 누수 발생",
    status: "검토중",
    photoLabel: "사진 — 이음부 누수 흔적",
    photoCount: 2,
    participants: 6,
    createdLabel: "오늘 등록",
    linkedPreReviewNo: 128,
    pin: { x: 55, y: 20 },
    updatedLabel: "방금 업데이트",
  },
  {
    no: 153,
    parentRoomId: "room-arch",
    title: "A동 3층 슬래브 철근 피복두께 검토",
    status: "검토중",
    assigneeId: "c-kim-sh",
    photoLabel: "사진 — 배근 상세",
    photoCount: 2,
    participants: 5,
    participantNames: ["품질팀 (보완 주장)", "현장소장 (재배근 주장)", "김대리", "이형탁 소장", "박품질 부장"],
    createdLabel: "야간 등록",
    isAfterHours: true,
    ageLabel: "3일째 진행중",
    floorplanLabel: "A동 3층 평면도",
    floorplanRev: "Rev.04 · 최신 승인본",
    pin: { x: 44, y: 46 },
    revLinked: { from: "Rev.04", to: "Rev.05" },
    updatedLabel: "10분 전 업데이트",
    aiSummary: {
      body: "스페이서 누락으로 피복두께 부족 가능성 제기. 재배근 결정, 재검측 대기중.",
      openItems: ["실제 피복두께 재측정", "품질담당자 최종 승인"],
      sourcesCases: 12,
      sourcesStandard: "사내 품질기준 3.2조",
    },
    completeForm: {
      reactionCount: 2,
      highValue: true,
      hasDisagreement: null,
      disagreeParties: [],
      priorities: [],
    },
  },
  {
    no: 151,
    parentRoomId: "room-arch",
    title: "지하 1층 방수 바탕면 하자 확인",
    status: "검토중",
    assigneeId: "c-park-jm",
    participants: 3,
    createdLabel: "3일 전 등록",
    isDormant: true,
    pin: { x: 24, y: 66 },
    updatedLabel: "3일간 응답 없음",
  },
  {
    no: 152,
    parentRoomId: "room-arch",
    title: "2층 계단실 거푸집 오시공 수정",
    status: "조치중",
    assigneeId: "c-kim-sh",
    participants: 4,
    createdLabel: "2일 전 등록",
    pin: { x: 70, y: 30 },
    updatedLabel: "1시간 전 업데이트",
  },
  {
    no: 149,
    parentRoomId: "room-arch",
    title: "외벽 커튼월 패널 줄눈 조정",
    status: "완료",
    assigneeId: "c-kim-sh",
    participants: 4,
    createdLabel: "지난주 등록",
    pin: { x: 60, y: 75 },
    updatedLabel: "어제 완료",
    techCase: {
      caseNo: "CASE-2026-0149",
      problem: "외벽 커튼월 패널 줄눈 간격 불균일",
      cause: "패널 제작 공차 누적",
      alternatives: "전체 재제작 vs 현장 심 조정",
      decision: "현장 심 조정 후 재시공",
      rationale: "공기 영향 최소화 · 외관 기준 충족",
      result: "재시공 후 검측 적합",
      prevention: "패널 반입 전 치수 전수검사 도입",
      approval: "approved",
    },
  },
  {
    no: 147,
    parentRoomId: "room-arch",
    title: "옥상 파라펫 방수 상세 확정",
    status: "완료",
    assigneeId: "c-park-jm",
    participants: 5,
    createdLabel: "지난주 등록",
    pin: { x: 60, y: 75 },
    updatedLabel: "2일 전 완료",
    techCase: {
      caseNo: "CASE-2026-0147",
      problem: "옥상 파라펫 방수 마감 상세 미확정",
      cause: "설계도서상 상세도 누락",
      alternatives: "노출방수 vs 누름방수",
      decision: "누름콘크리트 마감 적용",
      rationale: "유지관리 용이성 · 내구성",
      result: "상세도 승인 후 시공 착수",
      prevention: "설계 단계 상세도 체크리스트 반영",
      approval: "approved",
    },
  },
  {
    no: 131,
    parentRoomId: "room-arch",
    title: "지하 2층 방수 슬래브 조인트 처리",
    status: "완료·관찰중",
    participants: 5,
    createdLabel: "2026년 1월 28일 등록",
    updatedLabel: "6개월 전 완료",
    floorplanLabel: "B1F 슬래브 평면",
    pin: { x: 60, y: 75 },
    trace: { dueLabel: "6개월 경과", state: "관찰중" },
    techCase: {
      caseNo: "CASE-2026-0131",
      problem: "지하 2층 방수 슬래브 조인트 처리 미흡",
      cause: "조인트 실란트 시공 두께 부족",
      alternatives: "부분 보수 vs 전면 재시공",
      decision: "조인트 구간 재시공",
      rationale: "누수 재발 방지 · 하자보수 비용 절감",
      result: "재시공 후 담수시험 적합",
      prevention: "조인트 시공 후 담수시험 의무화",
      approval: "approved",
    },
  },
  {
    no: 154,
    parentRoomId: "room-civil",
    title: "되메우기 다짐도 기준 미달 구간 재시공 검토",
    status: "조치중",
    participants: 6,
    createdLabel: "오늘 등록",
    updatedLabel: "방금 업데이트",
  },
  {
    no: 155,
    parentRoomId: "room-mep",
    title: "지하 1층 소화배관 루트 협의",
    status: "검토중",
    participants: 5,
    createdLabel: "오늘 등록",
    updatedLabel: "방금 업데이트",
  },
  {
    no: 156,
    parentRoomId: "room-mep",
    title: "기계실 덕트 소음 저감 방안",
    status: "조치중",
    assigneeId: "c-choi-jw",
    participants: 4,
    createdLabel: "오늘 등록",
    updatedLabel: "방금 업데이트",
  },
];

export const seedMe: Me = {
  name: "이현우",
  rank: "공무 대리",
  company: "동부건설",
  site: "고창 물류센터 신축현장",
  trade: "공무",
  bizCardRegistered: false,
  activityPublic: false,
};

export const seedContacts: Contact[] = [
  {
    id: "c-kim-sh",
    name: "김성호 소장",
    rank: "현장소장",
    trade: "철근공사",
    tradeGroup: "건축",
    company: "동부건설",
    bizCardRegistered: true,
    bizCard: {
      nameEn: "KIM SUNG-HO",
      address: "전북 고창군 고창읍 월곡리 물류센터 신축현장",
      phone: "063-560-2100",
      fax: "063-560-2109",
      email: "sh.kim@dongbu.co.kr",
      mobile: "010-3245-8817",
    },
    lastTalkedLabel: "10분 전",
    activityPublic: true,
    activity: [
      { agendaNo: 153, title: "슬래브 철근 피복두께 검토", status: "검토중" },
      { agendaNo: 149, title: "커튼월 패널 줄눈 조정", status: "완료" },
      { agendaNo: 128, title: "옹벽 이음부 누수 사전검토", status: "완료·검증됨" },
    ],
  },
  {
    id: "c-park-jm",
    name: "박정민 부장",
    rank: "품질관리",
    trade: "구조",
    tradeGroup: "건축",
    company: "동부건설",
    bizCardRegistered: true,
    bizCard: {
      nameEn: "PARK JEONG-MIN",
      address: "전북 고창군 고창읍 월곡리 물류센터 신축현장",
      phone: "063-560-2101",
      fax: "063-560-2109",
      email: "jm.park@dongbu.co.kr",
      mobile: "010-4471-2298",
    },
    lastTalkedLabel: "어제",
    activityPublic: false,
    activity: [{ agendaNo: 153, title: "슬래브 철근 피복두께 검토", status: "검토중" }],
  },
  {
    id: "c-lee-ht",
    name: "이형탁 소장",
    rank: "현장소장",
    trade: "",
    tradeGroup: "건축",
    company: "삼우이엔지",
    bizCardRegistered: false,
    lastTalkedLabel: "3시간 전",
    activityPublic: false,
    activity: [],
  },
  {
    id: "c-choi-jw",
    name: "최재원 과장",
    rank: "기계설비",
    trade: "배관",
    tradeGroup: "설비",
    company: "한양기공",
    bizCardRegistered: true,
    bizCard: {
      nameEn: "CHOI JAE-WON",
      address: "전북 고창군 고창읍 월곡리 물류센터 신축현장",
      phone: "063-560-2140",
      fax: "063-560-2149",
      email: "jw.choi@hanyang-mech.co.kr",
      mobile: "010-9921-3345",
    },
    lastTalkedLabel: "2일 전",
    activityPublic: true,
    activity: [{ agendaNo: 156, title: "기계실 덕트 소음 저감 방안", status: "조치중" }],
  },
  {
    id: "c-jung-wj",
    name: "정우진 대리",
    rank: "소방설비",
    trade: "",
    tradeGroup: "설비",
    company: "세진소방",
    bizCardRegistered: false,
    lastTalkedLabel: "5일 전",
    activityPublic: false,
    activity: [],
  },
];

export const seedSites: Site[] = [
  {
    id: "site-gochang",
    name: "고창CDC 물류센터 신축공사",
    location: "전북 고창군 · A~C동",
    startDate: "2025. 4. 1",
    endDatePlanned: "2027. 12. 1",
    asOfDate: "2026. 8. 6",
    dDay: 481,
    timelinePct: 38,
    overallPlanPct: 44.2,
    overallActualPct: 41.6,
    progressLabel: "골조공사 · 62%",
    todayUpdateCount: 8,
  },
  {
    id: "site-pyeongtaek",
    name: "평택 반도체 P3 부대공사",
    location: "경기 평택시 · 전기·설비",
    progressLabel: "마감공사 · 88%",
    todayUpdateCount: 3,
  },
  {
    id: "site-cheongna",
    name: "청라 데이터센터 신축",
    location: "인천 서구 · 토목",
    progressLabel: "터파기 · 21%",
    todayUpdateCount: 5,
  },
];

export const seedContractors: ContractorCompany[] = [
  { id: "con-dongbu", siteId: "site-gochang", trade: "건축", companyName: "동부건설", status: "approved" },
  {
    id: "con-daemyung-elec",
    siteId: "site-gochang",
    trade: "전기",
    companyName: "대명전기",
    status: "approved",
  },
  {
    id: "con-safetech",
    siteId: "site-gochang",
    trade: "소방",
    companyName: "세이프테크소방",
    status: "approved",
  },
];

export const seedZones: Zone[] = [
  {
    id: "zone-rebar",
    siteId: "site-gochang",
    layer: "stack",
    x: 10,
    y: 58,
    width: 33,
    height: 23,
    date: "2026. 8. 6",
    registeredAt: "8/6 오전 9:12",
    registeredBy: "김성호 소장",
    materialType: "이형철근 HD25",
    quantity: "12톤",
    broughtInDate: "2026. 8. 6",
  },
  {
    id: "zone-formwork",
    siteId: "site-gochang",
    layer: "stack",
    x: 68,
    y: 20,
    width: 26,
    height: 18,
    date: "2026. 8. 6",
    registeredAt: "8/6 오전 8:40",
    registeredBy: "김성호 소장",
    materialType: "거푸집 자재",
    quantity: "8세트",
    broughtInDate: "2026. 8. 5",
  },
  {
    id: "zone-crane",
    siteId: "site-gochang",
    layer: "work",
    x: 10,
    y: 19,
    width: 26,
    height: 20,
    date: "2026. 8. 6",
    registeredAt: "8/6 오전 7:30",
    registeredBy: "김성호 소장",
    workContent: "B동 코어벽 타설",
    equipment: "타워크레인 1, 펌프카 1",
    workerCount: "8명",
  },
];

export const seedTrades: Trade[] = [
  {
    id: "tr-arch",
    siteId: "site-gochang",
    name: "건축",
    fixed: true,
    prevCumPlan: 52.0,
    prevCumActual: 49.4,
    weekPlan: 2.4,
    weekActual: 2.1,
    cumPlan: 54.4,
    cumActual: 51.5,
  },
  {
    id: "tr-elec",
    siteId: "site-gochang",
    name: "전기",
    fixed: true,
    prevCumPlan: 30.1,
    prevCumActual: 29.6,
    weekPlan: 1.8,
    weekActual: 1.9,
    cumPlan: 31.9,
    cumActual: 31.5,
  },
  {
    id: "tr-comm",
    siteId: "site-gochang",
    name: "통신",
    fixed: true,
    prevCumPlan: 18.0,
    prevCumActual: 17.2,
    weekPlan: 1.2,
    weekActual: 1.0,
    cumPlan: 19.2,
    cumActual: 18.2,
  },
  {
    id: "tr-fire",
    siteId: "site-gochang",
    name: "소방",
    fixed: true,
    prevCumPlan: 12.5,
    prevCumActual: 11.0,
    weekPlan: 1.0,
    weekActual: 0.6,
    cumPlan: 13.5,
    cumActual: 11.6,
    note: "인력부족",
  },
  {
    id: "tr-rebar",
    siteId: "site-gochang",
    name: "철근콘크리트",
    fixed: false,
    prevCumPlan: 61.0,
    prevCumActual: 60.2,
    weekPlan: 3.1,
    weekActual: 3.0,
    cumPlan: 64.1,
    cumActual: 63.2,
  },
];

export const seedWeeklyTotalRow: WeeklyTotalRow = {
  prevCumPlan: 42.0,
  prevCumActual: 40.3,
  weekPlan: 2.2,
  weekActual: 2.0,
  cumPlan: 44.2,
  cumActual: 41.6,
};

export const seedWeeklyPlan: number[] = [
  2.6, 2.8, 3.0, 3.1, 2.9, 3.2, 3.0, 2.8, 3.1, 3.0, 2.7, 2.9, 3.1, 2.8, 3.0, 2.2,
];
export const seedWeeklyActual: number[] = [
  2.4, 2.5, 2.9, 3.0, 2.6, 3.1, 2.8, 2.5, 3.0, 2.9, 2.4, 2.7, 2.9, 2.6, 2.7, 2.0,
];

export const seedTradeRequests: TradeRequest[] = [
  {
    id: "req-steel",
    siteId: "site-gochang",
    tradeName: "철골",
    companyName: "대명스틸",
    applicantName: "박정우",
    applicantRank: "부장 / 현장소장",
    requestedAt: "2026. 8. 6 08:24",
    status: "pending",
  },
  {
    id: "req-panel",
    siteId: "site-gochang",
    tradeName: "외장판넬",
    companyName: "거림이엔씨",
    applicantName: "최민석",
    applicantRank: "차장 / 공무팀",
    requestedAt: "2026. 8. 5 17:10",
    status: "pending",
  },
];
