"""회귀 기준(tests/metrics.json) 강제 — 담당: qa.

각 지표를 서비스 코드로 다시 계산해 기준 미달이면 실패한다(정확도류는 measured >= baseline, `*_max` 는 measured <= baseline).
측정값은 tests/metrics.measured.json 에 기록해 커밋한다(드리프트가 diff 로 보이도록). 기준 상향은 PR 에서 metrics.json 을 명시적으로 갱신.

지표 ↔ 완료 조건
- mapping_column_accuracy   : sync-2d3d  "기둥 매핑 정확도 ≥ 90%" (mapping.expected.json, A-COL)
- mapping_overall_accuracy  : sync-2d3d  전체 레이어(A-COL/S-BEAM/A-WALL/M-DUCT) 매핑 정확도
- scan_verdict_accuracy     : reality-capture "합성 점군 판정이 기대 enum 과 일치" (verdict.expected.json)
- registration_rmse_max     : reality-capture "기준점 3점으로 정합 후 rmse < max_rmse"
- activity_mapping_accuracy : progress-engine Activity↔객체 매핑 (schedule.expected.json, 3개 포맷 중 최솟값)
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from services.progress.activity_mapper import map_activities_to_objects, mapping_accuracy
from services.progress.importers import import_schedule
from services.scan.config import load_scan_config
from services.scan.pipeline import run_scan_pipeline
from services.sync.matcher import build_mappings
from services.sync.rules import load_layer_rules
from services.sync.transform import auto_align_by_grid, grid_from_ifc_objects
from tests.helpers import progress_fixtures as pf
from tests.helpers import scan_fixtures as sf
from tests.helpers import sync_fixtures as yf

TESTS = Path(__file__).resolve().parents[1]
BASELINE_PATH = TESTS / "metrics.json"
MEASURED_PATH = TESTS / "metrics.measured.json"
DRAWING_ID = "dwg-sample-1f"
SCHEDULE_FORMATS = ("schedule.csv", "schedule.xml", "schedule.xer")
ROUND = 4


def _lower_is_better(key: str) -> bool:
    return key.endswith("_max")


def _check(measured: dict[str, float], baseline: dict[str, float], key: str, value: float) -> None:
    """측정값을 기록하고 기준과 비교한다. 기준에 없는 키는 기록만 한다(extra)."""
    measured[key] = float(value)
    if key not in baseline:
        return
    if _lower_is_better(key):
        assert value <= baseline[key], f"{key}: measured {value:.4f} > baseline {baseline[key]:.4f} (regression)"
    else:
        assert value >= baseline[key], f"{key}: measured {value:.4f} < baseline {baseline[key]:.4f} (regression)"


@pytest.fixture(scope="module")
def baseline() -> dict[str, float]:
    data = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    assert data and all(isinstance(v, (int, float)) for v in data.values()), data
    return {k: float(v) for k, v in data.items()}


@pytest.fixture(scope="module")
def measured(baseline: dict[str, float]):
    """모듈의 모든 테스트가 측정값을 채우고, 종료 시(실패해도) metrics.measured.json 을 쓴다."""
    values: dict[str, float] = {}
    yield values
    report = {
        "_comment": "generated by tests/regression/test_metrics.py — do not edit by hand; baselines live in tests/metrics.json",
        "metrics": {k: round(values[k], ROUND) for k in sorted(baseline) if k in values},
        "extra": {k: round(v, ROUND) for k, v in sorted(values.items()) if k not in baseline},
        "baseline": dict(sorted(baseline.items())),
    }
    MEASURED_PATH.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


# ----------------------------------------------------------------- sync-2d3d
@pytest.fixture(scope="module")
def sync_inputs():
    entities, unit_scale = yf.load_dxf_entities()
    return entities, unit_scale, yf.load_ifc_objects(), yf.expected_mappings()


@pytest.fixture(scope="module")
def sync_mappings(sync_inputs):
    entities, _, objects, _ = sync_inputs
    return build_mappings(DRAWING_ID, entities, objects, yf.true_alignment(), level="1F")


def test_mapping_column_accuracy(sync_mappings, sync_inputs, measured, baseline):
    _, _, _, expected = sync_inputs
    acc, hit, n = yf.accuracy(sync_mappings, expected, {"A-COL"})
    print(f"\nmapping_column_accuracy={acc:.3f} ({hit}/{n})")
    _check(measured, baseline, "mapping_column_accuracy", acc)


def test_mapping_column_accuracy_auto_align(sync_inputs, measured, baseline):
    """자동 격자 정합 경로도 같은 기둥 기준을 만족해야 한다(사용자 정합값이 없는 도면)."""
    entities, unit_scale, objects, expected = sync_inputs
    gx, gy = grid_from_ifc_objects(objects)
    alignment = auto_align_by_grid(entities, gx, gy, load_layer_rules().grid_layers, unit_scale)
    assert alignment is not None
    mappings = build_mappings(DRAWING_ID, entities, objects, alignment, level="1F")
    acc, hit, n = yf.accuracy(mappings, expected, {"A-COL"})
    print(f"\nmapping_column_accuracy_auto_align={acc:.3f} ({hit}/{n})")
    measured["mapping_column_accuracy_auto_align"] = acc
    assert acc >= baseline["mapping_column_accuracy"], f"auto-align column accuracy {acc:.3f} < baseline"


def test_mapping_overall_accuracy(sync_mappings, sync_inputs, measured, baseline):
    _, _, _, expected = sync_inputs
    acc, hit, n = yf.accuracy(sync_mappings, expected)
    print(f"\nmapping_overall_accuracy={acc:.3f} ({hit}/{n})")
    _check(measured, baseline, "mapping_overall_accuracy", acc)
    # 기대쌍을 '다른 객체'로 매핑한 것은 정확도와 별개로 0건이어야 한다(틀린 매핑 > 매핑 없음)
    got = {m.entity_handle: m.global_id for m in sync_mappings}
    wrong = [h for h in expected if h in got and got[h] != expected[h]["global_id"]]
    assert wrong == [], wrong


# ----------------------------------------------------------------- reality-capture
@pytest.fixture(scope="module")
def scan_batch():
    cfg = load_scan_config()
    expected = sf.load_expected_verdicts()
    objects = sf.load_ifc_objects_1f(expected)
    batch = run_scan_pipeline(sf.SAMPLE_PLY, sf.load_alignment(), objects, scan_id="regression", cfg=cfg)
    return batch, expected, cfg


def test_registration_rmse_max(scan_batch, measured, baseline):
    batch, _, cfg = scan_batch
    reg = batch.registration
    assert reg.status == "ok", reg.message
    assert reg.rmse is not None
    print(f"\nregistration_rmse={reg.rmse:.4f} (config max_rmse={cfg.registration.max_rmse})")
    _check(measured, baseline, "registration_rmse_max", reg.rmse)
    assert reg.rmse < cfg.registration.max_rmse
    if reg.fitness is not None:
        measured["registration_fitness"] = float(reg.fitness)


def test_scan_verdict_accuracy(scan_batch, measured, baseline):
    batch, expected, _ = scan_batch
    acc, hit, n = sf.verdict_accuracy(batch.verdicts, expected["verdicts"])
    print(f"\nscan_verdict_accuracy={acc:.3f} ({hit}/{n})")
    _check(measured, baseline, "scan_verdict_accuracy", acc)
    assert all(v.state.value != "CONFIRMED" for v in batch.verdicts)


# ----------------------------------------------------------------- progress-engine
def test_activity_mapping_accuracy(measured, baseline):
    objects = pf.load_sample_objects()
    expected = pf.load_schedule_expected()["activity_object_mapping"]
    per_format: dict[str, float] = {}
    for filename in SCHEDULE_FORMATS:
        schedule = import_schedule(pf.FIXTURES / filename, "P-REG")
        mappings = map_activities_to_objects(schedule, objects)
        per_format[filename] = mapping_accuracy(mappings, expected)
        measured[f"activity_mapping_accuracy[{filename.split('.')[-1]}]"] = per_format[filename]
    worst = min(per_format.values())
    print(f"\nactivity_mapping_accuracy={worst:.3f} per_format={per_format}")
    _check(measured, baseline, "activity_mapping_accuracy", worst)


# ----------------------------------------------------------------- 무결성 (파일 순서상 마지막)
def test_every_baseline_metric_was_measured(measured, baseline):
    """metrics.json 에 기준만 추가하고 측정 테스트를 빠뜨리면 실패한다."""
    missing = set(baseline) - set(measured)
    assert not missing, f"baseline metrics without a measurement: {sorted(missing)}"
